# Generated by Django 3.1.7 on 2021-03-19 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20210315_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterdetail',
            name='chapter_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.chapter'),
        ),
    ]
