# Generated by Django 3.1.7 on 2021-03-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20210319_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterdetail',
            name='activity_desc',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='chapterdetail',
            name='material_desc',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='chapterdetail',
            name='video_lecture_desc',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
