# Generated by Django 3.2 on 2021-04-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_chapterdetail_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapterdetail',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
